%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{survstuff}
%\VignetteEncoding{UTF-8}
\documentclass{article}
%% \addtolength{\hoffset}{-1.2cm}
%% \addtolength{\textwidth}{2.4cm}
\usepackage{longtable}
% \usepackage[table]{xcolor}
%% \addtolength{\voffset}{-1cm}
%% \addtolength{\textheight}{2cm}

\title{Survival stuff}
\author{Henrik Renlund}

<<"setup", cache = FALSE, echo = FALSE, include = FALSE>>=
library(knitr)
library(data.table)
library(survival)
library(survivalist)
library(lattice)
## devtools::load_all() ## when testing
opts_chunk$set(include = TRUE,
               echo = TRUE,
               cache = FALSE,
               fig.pos = 'htb')
opts_knit$set(eval.after = c('fig.cap', 'fig.scap'))
if(FALSE){
    setwd('vignettes')
    knitr::knit2pdf("survstuff.rnw", clean = TRUE)
    shell.exec("survstuff.pdf")
}
@

\begin{document}

\maketitle
\tableofcontents
%% \newpage
%% \listoffigures
%% \listoftables
%% \newpage


\newpage
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Toy data and identification of time-to-event variables}

First we generate some data to apply our functions on:

<<"test-data">>=
n <- 1000
rnd <- function(set) sample(set, size = n, replace = TRUE)
set.seed(20260424)
d <- data.table(
    id = 1:n,
    male = rnd(0:1),
    group = factor(rnd(LETTERS[1:3]))
)
d[, `:=`(foo = rexp(n, 1/(1000 + 200 * male - 100 * as.integer(group))),
         bar = rexp(n, 1/(600 + 400 * male - 150 * as.integer(group))),
         cens = runif(n, min = 180, max = 810)
)]
d[, `:=`(ev.Foo = fifelse(foo <= cens, 1L, 0L),
         t.Foo = round(fifelse(foo <= cens, foo, cens)),
         ev.Bar = fifelse(bar <= cens, 1L, 0L),
         t.Bar = round(fifelse(bar <= cens, bar, cens)))]
d[, c("foo", "bar", "cens") := NULL]
str(d)
@

\texttt{Important note:} some functions can automatically detect time-to-event
variable pairs if they have a common pre- or suffix. By default this is
\texttt{t.} for the time- and \texttt{ev.} for the status component. This can be
changed within the options (documentation needed?).

\newpage

If you do not have this structure, you will need to give an "survival table" to
the the \texttt{surv} argument of these functions. This is a data frame with
columns \texttt{time}, \texttt{event}, and \texttt{label}. For the test data set
below this would be

<<"stab">>=
extract_stab_from_names(names(d))
@


\newpage
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Wrappers for survfit}

The function \texttt{survival::survfit} returns a list that is hard to work with
directly. The \texttt{suirvfitted} function is a simple wrapper that tidies the
output

<<"survfitted">>=
survfitted(Surv(t.Foo, ev.Foo) ~ group, data = d) |> str()
@

The function \texttt{survfit\_galore} is an extension of this idea that can
handle multiple outcomes and groupings at once. Groups defined by variables are
given in the formula argument, whereas a grouping that can contain overlaps has
to be given in the "grouping table" (\texttt{gtab}) argument

<<"survfit_galore">>=
gt <- d[, .("A / B" = group %in% LETTERS[1:2],
            "B / C" = group %in% LETTERS[2:3])]
sg <- survfit_galore( ~ male, data = d, gtab = gt)
@

Note that we did not specify a left hand side of the formula. As all
time-to-event components are identifiable with the default system of prefixes,
all time-to-event variables are used by default.

\newpage

The output we get here is easy to use immediately for e.g.\ plotting

<<"sg-plot", fig.cap = "An easy plot to make!">>=
xyplot(estimate ~ time | group + outcome, data = sg, group = male,
       type = c("s", "g"), lwd = 2, xlim = c(-10,740),
       auto.key = list(space = "top"),
       xlab = "Days since index",
       ylab = "Kaplain-Meier estimate") |>
    latticeExtra::useOuterStrips()
@

\newpage
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Time-to-event variable transformations}

A reference plot for the time-to-event variables in the toy data set

<<"ref-plot", fig.height = 4, fig.cap = "Reference plot for Foo and Bar.">>=
xyplot(1-estimate ~ time, data = survfit_galore( ~ 1, data = d),
       group = outcome, auto.key = list(space = "top"), type = c("s"), lwd = 2,
       xlab = "Days since index", ylab = "Kaplan-Meier estimate",
       xlim = c(-10, 740))
@

\newpage
%% =============================================================================
\subsection{Change the time scale}

A common transformation is to change the time scale of the time component of the
time-to event data. Here we have the test data time units in days, and we want
years. As all time-to-event components are identifiable with the default system
of prefixes, this is easily achieved

<<"rescale-1">>=
D <- rescale_surv(data = d, FUN = \(x) x/365.25, strip = FALSE)
str(D)
@

Note that \texttt{strip = FALSE} lets ut keep the entire data set (with only the
time components updated).

<<"rescale-plot", echo = FALSE, fig.height = 4, fig.cap = cap>>=
cap <- paste0("Changing the time scale.")
xyplot(1-estimate ~ time, data = survfit_galore( ~ 1, data = D),
       group = outcome, auto.key = list(space = "top"), type = c("s"), lwd = 2,
       xlab = "Years since index", ylab = "Kaplan-Meier estimate",
       xlim = c(-0.05, 2.05))
@



\newpage
%% =============================================================================
\subsection{Combined outcomes}

Sometimes one wants to combine two time-to-event variables into a single one.

<<"combine-1">>=
cs <- combine_surv(surv = c("Foo", "Bar"), data = D, strip = FALSE)
str(cs)
@

<<"cs-sanity-check", eval = FALSE, echo = FALSE>>=
cs[, table(ev.Foo, ev.Bar, ev.Combined, useNA = "if")]
@

<<"combine-1-plot", echo = FALSE, fig.height = 4, fig.cap = cap>>=
cap <- paste0("Combining time-to-event data into a single variable.")
xyplot(1-estimate ~ time, data = survfit_galore( ~ 1, data = cs),
       group = outcome, auto.key = TRUE, type = c("s"), lwd = 2,
       xlab = "Years since index", ylab = "Kaplan-Meier estimate",
       xlim = c(-0.05, 2.05))
@

\newpage
%% =============================================================================
\subsection{Truncation and landmarking}

There are functions for truncating (\texttt{truncate\_surv}) and landmarking
(\texttt{landmark\_surv}) time-to-event variables. In the example below
we do not reset the landmark data to 0 (as is the default) to illustrate what is
going on.

<<"trunc-landmark">>=
ts <- truncate_surv(data = D, trunc = 1, strip = FALSE)
ls <- landmark_surv(data = D, landmark = 1, strip = FALSE, reset = FALSE)
R <- rbind(ts[, type := "truncation"], ls[, type := "landmark"])
r <- survfit_galore( ~ type, data = R, t0 = FALSE)
@

<<"trunc-landmark-plot", echo = FALSE, fig.height = 4, fig.cap = cap>>=
cap <- paste0("Effect of truncating and landmarking.")
xyplot(1-estimate ~ time | outcome, data = r,
       groups = type, auto.key = list(space = "top"), type = c("s"), lwd = 2,
       xlab = "Years since index", ylab = "Kaplan-Meier estimate",
       xlim = c(-0.05, 2.05),
       panel = function(...){
           panel.abline(v = 1, lty = 2)
           panel.xyplot(...)
       })
@

<<"lattice-test--noeval", echo = FALSE, eval = FALSE>>=

## xyplot(1-estimate ~ time | outcome, data = r,
##        linetype = fifelse(r$male == 1, 1, 2),
##        groups = type, auto.key = list(space = "top"), type = c("s"), lwd = 2,
##        xlab = "Years since index", ylab = "Kaplan-Meier estimate",
##        xlim = c(-0.05, 2.05),
##        panel = function(...){
##            panel.abline(v = 1, lty = 2)
##            panel.xyplot(...)
##        })

xyplot(1-estimate ~ time | outcome, data = r,
       groups = type, auto.key = list(space = "top"), type = c("s"), lwd = 2,
       xlab = "Years since index", ylab = "Kaplan-Meier estimate",
       xlim = c(-0.05, 2.05),
       panel = function(x, y, ..., male = male){
           panel.abline(v = 1, lty = 2)
           ## panel.xyplot(x, y, lty = 1, ...)
           ## panel.xyplot(x, y, lty = 2, ...)
           panel.xyplot(x[male == 1], y[male == 1], lty = 1, ...)
           panel.xyplot(x[male == 0], y[male == 0], lty = 2, ...)
       })

@


\newpage
%% =============================================================================
\subsection{Surv:ifying time-to-event variables}

There is a function to convert time-to-event pairs into objects of class
\texttt{Surv}.

<<"Surv">>=
str(Survclass_surv(data = D, strip = FALSE))
@



\end{document}
