%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{survstuff}
%\VignetteEncoding{UTF-8}
\documentclass{article}
%% \addtolength{\hoffset}{-1.2cm}
%% \addtolength{\textwidth}{2.4cm}
\usepackage{longtable}
% \usepackage[table]{xcolor}
%% \addtolength{\voffset}{-1cm}
%% \addtolength{\textheight}{2cm}

\title{Survival stuff}
\author{Henrik Renlund}

<<"setup", cache = FALSE, echo = FALSE, include = FALSE>>=
library(knitr)
library(data.table)
library(survival)
library(survivalist)
library(lattice)
library(latticeExtra)
## devtools::load_all() ## when testing
opts_chunk$set(include = TRUE,
               echo = TRUE,
               cache = FALSE,
               fig.pos = 'htb')
opts_knit$set(eval.after = c('fig.cap', 'fig.scap'))
if(FALSE){
    setwd('vignettes')
    knitr::knit2pdf("survstuff.rnw", clean = TRUE)
    shell.exec("survstuff.pdf")
}
@

\begin{document}

\maketitle
\tableofcontents
%% \newpage
%% \listoffigures
%% \listoftables
%% \newpage


\newpage
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Toy data and identification of time-to-event variables}

First we generate some data to apply our functions on:

<<"test-data">>=
n <- 1000
rnd <- function(set) sample(set, size = n, replace = TRUE)
set.seed(20260424)
d <- data.table(
    id = 1:n,
    age = runif(n, 40, 80),
    sex = rnd(c("M", "F")),
    group = factor(rnd(LETTERS[1:2]))
)
d[, `:=`(foo = rexp(n, 1/(1900 + 500 * as.integer(sex == "M") -
                          300 * as.integer(group) +
                          2* age)),
         bar = rexp(n, 1/(2300 + 700 * as.integer(sex == "M") -
                          250 * as.integer(group) +
                          2.5 * age)),
         cens = runif(n, min = 180, max = 810)
)]
d[, `:=`(ev.Foo = fifelse(foo <= cens, 1L, 0L),
         t.Foo = round(fifelse(foo <= cens, foo, cens)),
         ev.Bar = fifelse(bar <= cens, 1L, 0L),
         t.Bar = round(fifelse(bar <= cens, bar, cens)))]
d[, c("foo", "bar", "cens") := NULL]
str(d)
@

\texttt{Important note:} some functions can automatically detect time-to-event
variable pairs if they have a common pre- or suffix. By default this is
\texttt{t.} for the time- and \texttt{ev.} for the status component. This can be
changed within the options (documentation needed?).

\newpage

If you do not have this structure, you will need to give an "survival table" to
the the \texttt{surv} argument of these functions. This is a data frame with
columns \texttt{time}, \texttt{event}, and \texttt{label}. For the test data set
below this would be

<<"stab">>=
extract_stab_from_names(names(d))
@


\newpage
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Wrappers for survfit}

The function \texttt{survival::survfit} returns a list that is hard to work with
directly. The \texttt{suirvfitted} function is a simple wrapper that tidies the
output

<<"survfitted">>=
survfitted(Surv(t.Foo, ev.Foo) ~ group, data = d) |> str()
@

The function \texttt{survfit\_galore} is an extension of this idea that can
handle multiple outcomes and groupings at once. Groups defined by variables are
given in the formula argument, whereas a grouping that can contain overlaps has
to be given in the "grouping table" (\texttt{gtab}) argument

<<"survfit_galore">>=
gt <- d[, .("A / B" = group %in% LETTERS[1:2],
            "B / C" = group %in% LETTERS[2:3])]
sg <- survfit_galore( ~ sex, data = d, gtab = gt)
@

Note that we did not specify a left hand side of the formula. As all
time-to-event components are identifiable with the default system of prefixes,
all time-to-event variables are used by default.

\newpage

The output we get here is easy to use immediately for e.g.\ plotting

<<"sg-plot", fig.cap = "An easy plot to make!">>=
xyplot(estimate ~ time | group + outcome, data = sg, group = sex,
       type = c("s", "g"), lwd = 2, xlim = c(-10,740),
       auto.key = list(space = "top"),
       xlab = "Days since index",
       ylab = "Kaplain-Meier estimate") |>
    latticeExtra::useOuterStrips()
@

\newpage
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Time-to-event variable transformations}

A reference plot for the time-to-event variables in the toy data set

<<"ref-plot", fig.height = 4, fig.cap = "Reference plot for Foo and Bar.">>=
xyplot(1-estimate ~ time, data = survfit_galore( ~ 1, data = d),
       group = outcome, auto.key = list(space = "top"), type = c("s"), lwd = 2,
       xlab = "Days since index", ylab = "Inverted Kaplan-Meier estimate",
       xlim = c(-10, 740), ylim = c(-0.05,1.05))
@

\newpage
%% =============================================================================
\subsection{Change the time scale}

A common transformation is to change the time scale of the time component of the
time-to event data. Here we have the test data time units in days, and we want
years. As all time-to-event components are identifiable with the default system
of prefixes, this is easily achieved

<<"rescale-1">>=
D <- rescale_surv(data = d, FUN = \(x) x/365.25, strip = FALSE)
str(D)
@

Note that \texttt{strip = FALSE} lets ut keep the entire data set (with only the
time components updated).

<<"rescale-plot", echo = FALSE, fig.height = 4, fig.cap = cap>>=
cap <- paste0("Changing the time scale.")
xyplot(1-estimate ~ time, data = survfit_galore( ~ 1, data = D),
       group = outcome, auto.key = list(space = "top"), type = c("s"), lwd = 2,
       xlab = "Years since index", ylab = "Inverted Kaplan-Meier estimate",
       xlim = c(-0.05, 2.05))
@



\newpage
%% =============================================================================
\subsection{Combined outcomes}

Sometimes one wants to combine two time-to-event variables into a single one.

<<"combine-1">>=
cs <- combine_surv(surv = c("Foo", "Bar"), data = D, strip = FALSE)
str(cs)
@

<<"cs-sanity-check", eval = FALSE, echo = FALSE>>=
cs[, table(ev.Foo, ev.Bar, ev.Combined, useNA = "if")]
@

<<"combine-1-plot", echo = FALSE, fig.height = 4, fig.cap = cap>>=
cap <- paste0("Combining time-to-event data into a single variable.")
xyplot(1-estimate ~ time, data = survfit_galore( ~ 1, data = cs),
       group = outcome, auto.key = TRUE, type = c("s"), lwd = 2,
       xlab = "Years since index", ylab = "Inverted Kaplan-Meier estimate",
       xlim = c(-0.05, 2.05))
@

\newpage
%% =============================================================================
\subsection{Truncation and landmarking}

There are functions for truncating (\texttt{truncate\_surv}) and landmarking
(\texttt{landmark\_surv}) time-to-event variables. In the example below
we do not reset the landmark data to 0 (as is the default) to illustrate what is
going on.

<<"trunc-landmark">>=
ts <- truncate_surv(data = D, trunc = 1, strip = FALSE)
ls <- landmark_surv(data = D, landmark = 1,
                    strip = FALSE, reset = FALSE)
R <- rbind(ts[, type := "truncation"], ls[, type := "landmark"])
r <- survfit_galore( ~ type, data = R, t0 = FALSE)
@

<<"trunc-landmark-plot", echo = FALSE, fig.height = 4, fig.cap = cap>>=
cap <- paste0("Effect of truncating and landmarking.")
xyplot(1-estimate ~ time | outcome, data = r, groups = type,
       auto.key = list(space = "top"), type = c("s"), lwd = 2,
       xlab = "Years since index", ylab = "Kaplan-Meier estimate",
       xlim = c(-0.05, 2.05),
       panel = function(...){
           panel.abline(v = 1, lty = 2)
           panel.xyplot(...)
       })
@

\newpage
%% =============================================================================
\subsection{Surv:ifying time-to-event variables}

There is a function to convert time-to-event pairs into objects of class
\texttt{Surv}.

<<"Surv">>=
str(Survclass_surv(data = D, strip = FALSE))
@

\clearpage
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Related to Cox regression}

%% =============================================================================
\subsection{Toy observational data}
<<"obs-data", echo = FALSE, include = TRUE, results = 'asis'>>=
n <- 1000
logistic <- function(z) 1 / (1 + exp(-z))

set.seed(20260430)
OD <- data.table(
    id = 1:n,
    male = factor(rbinom(n, 1, 0.5), levels = 0:1,
                  labels = c("Female", "Male")),
    age = runif(n, 40, 80)
)
OD[, old := as.integer(age > median(age))]
OD[, pe := logistic(2 - log(1.5)*(male == "Male") - .04 * age)]
OD[, E := factor(rbinom(n, 1, pe), levels = 0:1,
                 labels = c("ctrl", "case"))]
## OD[, table(E)]
## OD[, table(E, male)]
## OD[, table(E, old)]

OD[, pu := logistic(-4 + 0.02 * age +
                    log(1.5) * (male == "Male") +
                    log(1.3) * (E == "case"))]
OD[, Y := rexp(n, rate = pu)]
OD[, cens := runif(n, 1, 10)]
OD[, ev.U := as.integer(Y <= cens)]
OD[, t.U := fifelse(ev.U == 1, Y, cens)]

## sf0 <- survfitted(Surv(t.U, ev.U) ~ E, data = OD)
## xyplot(1-estimate ~ time, data = sf0, groups = E, type = "s")
## sf <- survfitted(Surv(t.U, ev.U) ~ E + male + old, data = OD)
## xyplot(1-estimate ~ time | male + old, data = sf, groups = E,
##        type = "s")
## coxph(Surv(t.U, ev.U) ~ E, data = OD)
## coxph(Surv(t.U, ev.U) ~ E + male, data = OD)
## coxph(Surv(t.U, ev.U) ~ E + age, data = OD)
## coxph(Surv(t.U, ev.U) ~ E + male + age, data = OD)

OD[, c("pe", "pu", "Y", "cens") := NULL]

g <- dable::dguide(OD, id = "id")
b <- dable::baseline(OD, guide = g, gtab = "E")
dable::blatex(b, caption = "Toy obesrvational data", label = "tab:OD")

@

<<"cr_bias--sanity-check", echo = FALSE, eval = FALSE>>=

coxph(Surv(t.U, ev.U) ~ E + male + age, data = OD)
coxreg_bias(data = OD,
            surv = "U",
            main = "E",
            bnry = "male")
coxreg_bias(data = OD,
            surv = "U",
            main = "E",
            bnry.manual = list("male2" = c(1.480123, 0.5336538, 0.4547872)))

@


\clearpage
%% =============================================================================
\subsection{Main exposure sensitivity to adjustment variables}

The function \texttt{coxreg\_change} calculates the hazard ratio for the main
(binary) exposure under permutations of the full adjustment model. The return
value is a data frame grouped by the column \texttt{change} whose values
indentidy

\begin{itemize}
  \item \texttt{univariate} effect (on main exposure) of adjusting for 1
    variable (in isolation)
  \item \texttt{full} effect of subtracting 1 variable (in isolation) from the
    full model
  \item \texttt{sequential\_inclusion} effect of adding variables sequentially
    (from unadjusted to the full model)
  \item \texttt{sequential\_exclusion} effect of subtracting variables
    sequentially from the full model
\end{itemize}

<<"coef-sens">>=
coxreg_change(
    data = OD,
    surv = data.frame(label="U",time="t.U",event="ev.U"),
                              ## 'stab' or common name of surv-pairs
    main = "E",               ## exposure term
    terms = c("male", "age"), ## adjustment variables
    uni = TRUE,               ## univariate effects?
    full = TRUE,              ## fully adjusted effects?
    inc = TRUE,               ## sequential inclusion?
    exc = TRUE                ## sequential exclusion?
)

@


%% =============================================================================
\subsection{Confounder bias}

In observational studies the major difficulty is the possibility of (unknown)
counfounding. The function \texttt{coxreg\_bias} examines the effect of the main
exposure - assumed to be binary - if additional coundfounding variables could
have been adjusted for.

<<"cr-bias-1">>=
coxreg_bias(
    data = OD,
    surv = "U",
    main = "E",    ## exposure term
    bnry = "male", ## binary adjustment variables
    real = "age"   ## real (continuous) adjustment variables
)[, c(1:2, 4:6, 9:11)]
@


In the output we see the mean value of adjustment variables in the two binary
states of the exposure (\texttt{stat0} and \texttt{stat1}, respectively).  We
can see what the coefficients are in an adjusted analysis for each term
(\texttt{adjHR}), but more interestingly we can see what the coefficient on the
main exposure would be (\texttt{mainHR}) if we could adjust for an additional
confounder with the same association to both the outcome and exposure as the
given variables, as well as the lower and upper part of the confidence interval
(\texttt{mainHR.l} and \texttt{mainHR.u}, respectively).

\newpage
We can "manually" add hypothetical confounder with a given association to the
outcome - given as a hazard ratio - and to the exposure - given as the mean
level at the 2 different states.

<<"cr-bias-2">>=
cb <- coxreg_bias(data = OD,
                  surv = "U",
                  main = "E",
                  bnry = "male",
                  real = "age",
                  bnry.manual = list("confB" = c(1.3, .55, .45)),
                  real.manual = list("confR" = c(1.01, 50,  50)))
cb[, c(1, 3:5, 9:11)]
r <- attr(cb, "tidy")
@

<<"cr-bias-plot", echo  =FALSE,  fig.cap = cap>>=
stripplot(alt ~ HR | eff, data = r, pch = 16, cex = 1.2,
          x0 = r$ci1, x1 = r$ci2,
          xlim = c(min(r$ci1) - 0.05, max(r$ci2) + 0.05),
          panel = function(x, y, x0, x1, ...){
              panel.grid(h = -1, v = -1)
              panel.abline(v = 1, lty = 2)
              panel.segments(x0 = x0, x1 = x1, y0 = y, y1 = y)
              panel.stripplot(x, y, ...)
          },
          xlab = "Adjusted hazard ratio for main effect")

cap <- paste0("Adjusted hazard ratio for main effect when adjusting ",
              "for age and sex, as well as a confounder U ",
              "specified in the figure.")
@


\clearpage
%% =============================================================================
\subsection{Helpers for time-dependent covariates}

It is the authors firm opinion that it is generally much easier to assemble your
time-dependent data set with a global clock, i.e. all variables related to time
is the same - even though we often want individual clocks (typically each
subject starts with \texttt{tstart = 0}) at a later stage.

<<"tdc-raw", echo = FALSE>>=
POP <- rowwiseDT(
    id=,       entry=,        exit=,
      1, "2020-01-11", "2020-04-10",
      2, "2020-01-21", "2020-07-19"
)
POP[, `:=`(entry = as.Date(entry), exit = as.Date(exit))]
FOO <- rowwiseDT(
    id=,        date=,
      1, "2020-01-31",
      1, "2020-03-11",
      2, "2020-05-30"
)
FOO[, `:=`(date = as.Date(date))]
MED <- rowwiseDT(
    id=,        date=, med=,
      1, "2019-12-27",  "A",
      1, "2020-02-20",  "B",
      2, "2020-01-01",  "B",
      2, "2020-01-31",  "C",
      2, "2020-02-05",  "B"
)
MED[, `:=`(date = as.Date(date))]
@

So we have data on the toy study population

<<"tdc-pop">>=
print(POP)
@

and the events

<<"tdc-foo">>=
print(FOO)
@

as well as medications

<<"tdc-med">>=
print(MED)
@

Now, one could work with dates directly, but integers are easier to grasp and
takes up less space.

<<"tdc-data-0">>=
.d0 <- as.Date("2020-01-01")
POP[, `:=`(tstart = time_date2num(entry, ref = .d0),
           tstop = time_date2num(exit, ref = .d0))][]
FOO[, `:=`(t = time_date2num(date, ref = .d0))][]
MED[, `:=`(t = time_date2num(date, ref = .d0))][]
@

Now we use \texttt{survival::tmerge} to build the data set

<<"tdc-data">>=
T0 <- tmerge(POP, POP, id = id, tstart = tstart, tstop = tstop)
T1 <- tmerge(T0, FOO, id = id, foo = event(t))
T2 <- tmerge(T1, MED, id = id, drug = tdc(t, med, init = ""))
T2
@

\newpage
We might be interested in going back to working with dates at some point

<<"tdc-time-revert">>=
as.data.table(T2)[, `:=`(entry = NULL, exit = NULL,
                         dstart = time_num2date(tstart, ref = .d0),
                         dstop = time_num2date(tstop, ref = .d0))][]
@

Even though resetting each subjects clock to start at 0 is easy, there is a
function to that end

<<"tdc-reset-time">>=
(T3 <- tstart2zero(T2, id = "id"))
@

In this data set we allow multiple instances of the event 'foo'. Often we only
follow subjects until the first occurence.

<<"tdc-truncate-at-first-event">>=
event1trunc(T3, id = "id", event = "foo")
@

Other times, one might be interested in converting states to events

<<"tdc-state2evet">>=
state2event(state = "drug", by = "id", data = T3)
@

although note that these 'events' does not survive further applications of
\texttt{tmerge}, for that you have to utilize \texttt{tmerge} itself.

\clearpage
%% =============================================================================
\subsection{Describing time-dependent covariates}

There are a couple of functions to describe the evolution of time-dependent
variable on the population level.

Here is a toy data set on 3 subjects and their treatment (\texttt{trt} 0/1) and
more specifically \emph{type} (\texttt{type} A/B) of treatment

<<"desc-tdc-data">>=
POP <- data.table(id = 1:3, tstart = 0, tstop = 100)
S <- rowwiseDT(
    id=, t=, trt=, type=,
    1,    5,    1,   "A",
    2,   10,    1,   "A",
    3,   15,    1,   "A",
    1,   20,    0,   " ",
    2,   25,    0,   " ",
    1,   25,    1,   "B",
    3,   30,    0,   " ",
    2,   30,    1,   "B",
    3,   35,    1,   "B"
)
T0 <- tmerge(POP, POP, id = id, tstart = tstart, tstop = tstop)
(T1 <- tmerge(T0, S, id = id, trt = tdc(t, trt, init = 0)))
@

\newpage
The function \texttt{tdc\_statistic} can be used to create a statistic for a
single variable, you need to specify the variable as well as supply a function
that takes a single vector input.

<<"desc-tdc-1">>=
tdc_statistic(T1, var = "trt", FUN = mean)
tdc_statistic(T1, var = "trt", FUN = \(x){
    c(mean = mean(x), sum = sum(x))
})
@

\newpage
The function \texttt{tdc\_calculator} is more general; it takes a function that
takes a data frame as input.

<<"desc-tdc-2">>=
(T2 <- tmerge(T1, S, id = id, type = tdc(t, type, init = " ")))
tdc_calculator(T2, FUN = \(d){
    with(d, data.frame(trt = sum(trt),
                       A = sum(type == "A"),
                       B = sum(type == "B")))
})
@

\end{document}
